### ISSUE TITLE
calmis aminakoyim

### ISSUE THREAD

**Issue by erdemhglu** [kaanmutlu17/kaanmutlu17#1]
%100 html ve css bilgisiyle nasil caliyon ya aciz olan bendim bide dimi 
https://onlineprofitdeals.com/ellie-pre-launch-landing-page-onlineprofitdeals/

**Comment by tarikcoskun** [comment]
https://depremx.org/ - https://cruip.com/demos/ellie/
https://tuval.co/ - https://cruip.com/demos/solid/

"I develop web sites." TM KARDEŞİM

**Comment by eren885** [comment]
calmis aminakoyim

**Comment by erdemhglu** [comment]
hâla çalıyon mu
